### PR TITLE
Shall we include integration tests into coverage report?

### PR DESCRIPTION
**Pull request by vogdb**
Just a thought to think of.

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by vogdb** [comment]
@zazabe please hold

**Comment by vogdb** [comment]
@ppp0 need your opinion here. Is it possible to run integration tests on Travis? They require a running vagrant machine.

**Comment by ppp0** [comment]
>They require a running vagrant machine.
 
Who requires an additional VM:
- Travis CI?
- the tests?

Consider that Virtualbox can't run inside Travis - because it's a virtualized machine there, too.
I really like the proposed direction in here: https://github.com/travis-ci/travis-ci/issues/6060#issuecomment-221395944

We do have a vagrant box version for Amazon EC2 where one could run janus standalone and have the tests connect to it.

Mocking the traffic would be a feasible solution? Probably difficult... or you know some nice tools?

**Comment by zazabe** [comment]
Is it possible to use https://docs.travis-ci.com/user/docker/, with https://hub.docker.com/r/jess/chrome/ for example?

**Comment by ppp0** [comment]
Interesting @zazabe !
* chrome/chromedriver: something like https://hub.docker.com/r/robcherry/docker-chromedriver/
* janus standalone.. there are some builds (https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=janus&starCount=0) but I think we'd be better off by providing our own janus container

**Comment by vogdb** [comment]
> Who requires an additional VM:
- Travis CI?
- the tests?

the tests.

So, shall we use Docker instead of Vagrant in this project? @ppp0 @zazabe

**Comment by ppp0** [comment]
Would be really cool to have a containerized janus-gateway (there are a few around already but they were not invented here plus they might not be configured the way we want) see https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=janus&starCount=0

**Comment by vogdb** [comment]
> So, shall we use Docker instead of Vagrant in this project? @ppp0 @zazabe 

@njam please share your thoughts too

**Comment by njam** [comment]
Tomasz and I created a docker container of our janus-gateway puppet modules during research day: https://github.com/cargomedia/docker-images
It uses our Puppet modules to install and configure the software, so it's exactly the same setup, including our plugins that we use (rtpbroadcast, audioroom).

**Comment by ppp0** [comment]
Nice! As soon as I have some time, I will look into this issue!

**Comment by njam** [comment]
Closing due to https://github.com/cargomedia/janus-gateway-js/issues/99

**Pull request closed without merging**
