### PR TITLE
Take into account createOffer and createAnswer options

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
This PR is about [the note](https://github.com/cargomedia/janus-gateway-js/pull/37#issuecomment-226178075)

> - we could handle more options:   
```
  audioSend: false,
  audioRecv: false,
  muted: false
```

I decided to not create those shortcut options such as `audioSend` and `audioRecv`. I just moved `RTCOfferOptions` to params of `startStream`.
@zazabe wdyt? Shall we have those shortcut options still?

**Comment by zazabe** [comment]
As you want, we can always add these shortcuts at a higher level, like `AudioRoomPlugin` in the future... but yes, being able it set the `RTCOfferOptions` is required (and already available in `MediaPlugin` anyhow).

**Comment by vogdb** [comment]
@zazabe can I merge then?

**Comment by zazabe** [comment]
yep

**Pull request merged**
