### PR TITLE
Delegate destroy/close events down

### PR DESCRIPTION
**Pull request by vogdb**
on Connection `close` event -> trigger `destroy` event on each Session
on Session `destroy` event -> trigger `detach` event on each Plugin

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka wdyt about this approach?

**Comment by tomaszdurka** [comment]
Looks good.

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
lgtm

**Pull request merged**
