### PR TITLE
Runner for integration tests

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
Currently one integration test fails. I suspect that Chromium that we use from puppet is outdated cause this test works fine on my laptop where Chromium and Chrome are latest. @ppp0 Is Chromium version 48 the latest one? We have it on vagrant machine. Can we possibly update it?

**Comment by vogdb** [comment]
@ppp0 ?

**Comment by ppp0** [comment]
Since we install chromium via deb package I believe the current version is chromium-browser 48.0.2564.82-0ubuntu0.15.04.1.1193 (universe) (see https://launchpad.net/ubuntu/vivid/+source/chromium-browser)

**Comment by ppp0** [comment]
To have the latest version, we probably would need to install it differently, see http://www.chromium.org/getting-involved/dev-channel/

**Comment by vogdb** [comment]
Ok, I will try manually find the min required version and let you know

**Comment by vogdb** [comment]
@ppp0 I need version 51.0 at least. Please provide the necessary installation steps.

**Pull request merged**
