### PR TITLE
Add docu about testing and releasing

### PR DESCRIPTION
**Pull request by vogdb**
- Run tests locally 
- Release a new version

See https://github.com/cargomedia/guides/tree/master/software-projects

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please look
@njam FYI

**Comment by zazabe** [comment]
lgtm, maybe we could also add a `LICENSE` file? like in https://github.com/cargomedia/cm/blob/master/LICENSE

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm!

**Pull request merged**
