### PR TITLE
Proper docu for Promises

### PR DESCRIPTION
**Pull request by vogdb**
https://github.com/jsdoc3/jsdoc/issues/509

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
Seems this discussion is still ongoing and there's multiple propositions at the end...

We could use this syntax to describe the fulfill/reject value(s), but we should also keep the `@returns {Promise}` for the IDE completion, wdyt?

**Comment by vogdb** [comment]
> We could use this syntax to describe the fulfill/reject value(s), but we should also keep the `@returns {Promise}` for the IDE completion, wdyt?

Does IDE really use this `@returns {Promise}`? I always have a bunch of unrelated autocompletion for functions with such JSDoc. How autocompletion breaks for you if you use smth like this:
``` @promise {Object} result ``` ?

**Comment by zazabe** [comment]
screen shot 2016-06-24 at 11 29 10
screen shot 2016-06-24 at 11 29 43

I just mean that we could introduce new tags like `@promise` or `@fulfilled/@rejected` and keep `@returns` at the same time. 
But maybe `@returns {Promise.<string|Error>}` could be enough compared to `@promise {string}`...

**Comment by vogdb** [comment]
@zazabe please look on this solution

**Comment by zazabe** [comment]
- we should always use `@returns` instead of the `@return` alias
- not sure about the `@fulfilled` syntax, should we follow the same rules than for [`@params`](http://usejsdoc.org/tags-param.html#names-types-and-descriptions)?   
  in b71a205, the second parameter could be either the description or the name, I think we should always have the name (+ hyphen?) if there's a description. Also, sometimes the first parameter is directly the description, which seems strange compared to other jsdoc tags.

**Comment by vogdb** [comment]
@zazabe please review

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm!

**Pull request merged**
