### PR TITLE
Timer specs

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka please review

**Comment by tomaszdurka** [comment]
I'm not sure about the whole Timer class, but let's say it's good...

**Comment by tomaszdurka** [comment]
Maybe try to make the specs bit more explaining.

E.g.

`it('executes callback on reset')`, `it('executes callback after timeout')` or so. Otherwise it's hard to understand without going into the code.

**Comment by tomaszdurka** [comment]
In case of comments like that I would appreciate a comment with/before merge - just for clarification.

**Pull request merged**
