### PR TITLE
Plugin register mechanism

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@tomaszdurka or @zazabe please review.

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm, just not sure if it should throw when the plugin name is not registered in `Plugin.create`...

**Comment by vogdb** [comment]
well, we can always change that behavior. For now I wouldn't do it cause we haven't implemented all the plugins.

**Comment by zazabe** [comment]
Yep, seems good to me

**Pull request merged**
