### PR TITLE
Missing handlers for `webrtcup`, `media`, `hangup`

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
well, here are the changes. @zazabe please reject/confirm them. I'm still unsure about having them. btw the original janus.js does not have callbacks for those events https://janus.conf.meetecho.com/docs/JS.html

**Comment by vogdb** [comment]
@zazabe wdyt?

**Comment by zazabe** [comment]
I think only `hangup` is useful as an event, others could be catch by listening on `message` as you said.

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm!

**Pull request merged**
