### PR TITLE
Rename peer connection events

### PR DESCRIPTION
**Pull request by vogdb**
'addstream' => 'pc:track'
_onTrickle 'error' => 'pc:error'

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
It seems that [`RTCTrackEvent`](https://www.w3.org/TR/webrtc/#rtctrackevent) provide a `FrozenArray<MediaStream>` but we [`addstream`](https://developer.mozilla.org/en-US/docs/Web/Events/addstream) gives  a `MediaStream`, not sure if it's good to mix them into the same `pc:track` event, wdyt?

**Comment by vogdb** [comment]
I agree. I just read that `onaddstream` is deprecated and `ontrack` is a replacement for it. I supposed that `ontrack` will preserve the previous syntax. My fault.
@zazabe please look

**Comment by zazabe** [comment]
lgtm!

**Comment by vogdb** [comment]
🎉

**Pull request merged**
