### PR TITLE
Vagrant box with chromium for auto tests

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by vogdb** [comment]
I have this error during provision
```
==> default: Error: Evaluation Error: Error while evaluating a Function Call,
Could not find template 'janus-gateway-js/install.sh.erb'
at /tmp/vagrant-puppet/environments/development/manifests/site.pp:8:16 on node janus-gateway-js.dev.cargomedia.ch
```

This file is presented in the PR but it gets deleted every time I do a provision. Like there is a mechanism that cleans all modules including ours.

**Comment by ppp0** [comment]
Yes, this is an open issue. As you have noticed, Librarian-puppet overwrites the whole modules directory and wipes things that are meant to be excluded. It's likely a small config issue, may be @njam knows what is wrong. Setting [this](https://github.com/cargomedia/janus-gateway-js/pull/54/files#diff-508876f76614ef7318184cdbe040ba57R2) to `false` did not work, unfortunately

**Comment by njam** [comment]
librarian-puppet installed modules should not be mixed with checked in modules.
See for example [denkmal](https://github.com/denkmal/denkmal.org/tree/master/puppet).

**Comment by vogdb** [comment]
@ppp0 can you adjust please?

**Comment by ppp0** [comment]
@vogdb now it boots and provisions

**Pull request merged**
