### PR TITLE
Split current plugin name on package and name

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
if it's about getting the name used in janus response to notify about a specific action/event, like `"streaming": "list"` in https://github.com/cargomedia/janus-gateway-rtpbroadcast#list, just be careful, because not all plugins use the last part of the package name as this name. (eg. `package=janus.plugin.cm.rtpbroadcast / name-in-response=streaming`).

If it's about that, maybe you could override `getShortName()` of `RtpbroadcastPlugin` plugin?

**Comment by vogdb** [comment]
> if it's about getting the name used in janus response to notify about a specific action/event, like `"streaming": "list"`

yes.
Now I'm thinking that it will be useful to have two methods:
 - `getName` for the name that is used for attachment
 - `getResponseAlias` for the name that is used in response

Both of them should explicitly state names without any implicit logic like "the last part of the package name". Possibly #94 might solve this if we introduce a hierarchy of Transaction/PluginResponses for plugins.

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
maybe integration tests should be updated then? or there's something in preparation to avoid `response.getData(plugin.getResponseAlias())`?

**Comment by vogdb** [comment]
they will be updated in #94

**Pull request merged**
