### PR TITLE
Streaming plugin integration tests

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by zazabe** [comment]
not tested but i guess i will have the same problem than here : https://github.com/cargomedia/janus-gateway-js/pull/59#issuecomment-230702200

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
Seems only `it.only('streams video', ...)` is tested, any reason?

**Comment by zazabe** [comment]
- I removed the `it.only` and it works!
- why `this.timeout(20000);` ? the `streams video` test fails if i remove it...

**Comment by vogdb** [comment]
> - I removed the `it.only` and it works!

It is fixed in #59 :D

> - why `this.timeout(20000);` ? the `streams video` test fails if i remove it... 

I need kris-lab assistance on this. Somehow it takes so much time to stream >_<.

**Comment by zazabe** [comment]
so let's merge it like that ;)

**Pull request merged**
