### PR TITLE
Audiobridge integration test

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
I tried to run the AudioBridge test, but the vagrant box is not configured with this plugin... is it hard to add "native" janus plugin support ? `janus.plugin.audiobridge` and `janus.plugin.streaming`?

**Comment by zazabe** [comment]
@kris-lab some thoughts about https://github.com/cargomedia/janus-gateway-js/pull/59#issuecomment-230702200?

**Comment by vogdb** [comment]
@kris-lab please ignore zazabe's note. We will resolve it on our own. In order to enable janus native plugins you need to link them into `/lib/janus/plugins.enabled/` and copy their configs in `/etc/janus/`. I will send the commands to you.

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
got this error on `vagrant provision`:
```
$ vagrant provision
==> default: Installing Puppet modules in "puppet" with Librarian-Puppet...
==> default: Running provisioner: puppet...
==> default: Running Puppet with environment development...
==> default: stdin: is not a tty
==> default: Notice: Compiled catalog for janus-gateway-js.dev.cargomedia.ch in environment development in 0.72 seconds
==> default: Notice: /Stage[main]/Main/Node[default]/Janus::Role::Standalone[janus]/Janus::Server[janus]/Janus::Server::Setup_dirs[janus]/File[/opt/janus-cluster/janus/etc/janus/janus.plugin.streaming.cfg]/ensure: removed
==> default: Notice: Applied catalog in 0.31 seconds
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: ln:
==> default: failed to create symbolic link `/opt/janus-cluster/janus/usr/lib/janus/plugins.enabled/libjanus_streaming.so'
==> default: : File exists
```

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lvgtm! :)

**Pull request merged**
