### PR TITLE
Install chrome 51 and later

### PR DESCRIPTION
**Pull request by ppp0**
Part of #66

### CODE REVIEW

**Comment by vogdb** [comment]
@ppp0 installation of Chrome has problems. I fixed what I could but I don't know how to deal with:
```
==> default: Error: 
==> default: mkdir -p /tmp/86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: cd /tmp/86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: echo \#\!/bin/bash\ -e'
==> default: ''
==> default: 'curl\ -sL\ \"https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64\%2f386257\%2fchrome-linux.zip\?alt\=media\"\ \>\ chrome-linux.zip'
==> default: 'unzip\ -ud\ /usr/local\ chrome-linux.zip'
==> default: 'ln\ -s\ ../local/chrome-linux/chrome\ /usr/bin/chromium-browser'
==> default: 'chmod\ \+x\ /usr/bin/chromium-browser'
==> default: ' > 86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: chmod +x 86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: ./86ff557e6ba8e302ef1cc7d60f716681 returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Main/Node[default]/Helper::Script[install chrome browser]/Exec[exec install chrome browser]/returns: change from notrun to 0 failed: 
==> default: mkdir -p /tmp/86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: cd /tmp/86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: echo \#\!/bin/bash\ -e'
==> default: ''
==> default: 'curl\ -sL\ \"https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64\%2f386257\%2fchrome-linux.zip\?alt\=media\"\ \>\ chrome-linux.zip'
==> default: 'unzip\ -ud\ /usr/local\ chrome-linux.zip'
==> default: 'ln\ -s\ ../local/chrome-linux/chrome\ /usr/bin/chromium-browser'
==> default: 'chmod\ \+x\ /usr/bin/chromium-browser'
==> default: ' > 86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: chmod +x 86ff557e6ba8e302ef1cc7d60f716681 && \
==> default: ./86ff557e6ba8e302ef1cc7d60f716681 returned 1 instead of one of [0]
```

**Comment by vogdb** [comment]
it happens on `vagrant provision`

**Comment by ppp0** [comment]
Depends on https://github.com/cargomedia/puppet-packages/pull/1388

**Comment by ppp0** [comment]
@vogdb please check

**Comment by vogdb** [comment]
Something is wrong with permissions. Unless I do `sudo chown -R vagrant /usr/local/chrome-linux/`, tests do not run.

**Comment by vogdb** [comment]
Still have this problem. Verified twice with destroying the box.

**Comment by vogdb** [comment]
@ppp0 FYI

**Pull request merged**
