### PR TITLE
RtpBroadcastPlugin

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
Should/could I test it with the bulldog box?

**Comment by vogdb** [comment]
Yes, you should be able but I would suggest to use janus service directly!

**Comment by vogdb** [comment]
@zazabe please hold with the review here

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
tested, looks very good to me ;) 

_Note: I can't test the `janus.plugin.streaming` but I trust you did _

**Comment by vogdb** [comment]
I tested! @zazabe please review

**Comment by zazabe** [comment]
lgtm!

**Pull request merged**
