### PR TITLE
Refactor common plugin code

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review. It should be easier to review commit-by-commit. Pay special attention to @	2c11d04

**Comment by zazabe** [comment]
- e3d2c95
  - I wrote a note about having a generic method to send transactions, then i saw your last commit :) (5c925c3)
  - now I'm wondering, is it really useful to have this `TCrudPlugin`? 
  - why not changing `sendWithDefaultTransaction(options)` into `sendWithTransaction(message, callback)`, then `callback` could be executed after the common `response['plugindata']['data']['error']` check ?

- 2c11d04:   
  OK, get it, I have a better understanding about how it works ;) so if i understand, `transaction.execute` is just resolving/rejecting the `transaction.promise` from outside and `sendSync` has a ref to this transaction.promise and will react to it.   
  Sgtm, even if it smells the [deferred antipattern](http://stackoverflow.com/questions/23803743/what-is-the-explicit-promise-construction-antipattern-and-how-do-i-avoid-it) a bit, (something external is resolving/rejecting the transaction.promise), it don't think we can really avoid it. We could resolve/reject it based on some event but it will be quite the same :).

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm

**Pull request merged**
