### PR TITLE
Externalize vendor dependencies

### PR DESCRIPTION
**Pull request by vogdb**

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
- `"exorcist": "^0.4.0"` is missing from `package.json`
- `gulp` warning: `gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.`

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
is there any reason to not have `jquery` in vendor?

**Comment by vogdb** [comment]
jquery is not a dependency of janus-gateway-js. It is used only in examples.

**Comment by zazabe** [comment]
ah yes, right, so lgtm!

**Pull request merged**
