### PR TITLE
Create mechanism to hook plugins from outside

### PR DESCRIPTION
**Pull request by vogdb**
Also to think. Shall we move plugins outside to their separate repos?

### CODE REVIEW

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm, just a small note, here https://github.com/cargomedia/janus-gateway-js/pull/52/files#diff-04c6e90faac2675aa89e2176d2eec7d8R15, we should also pass the connection id.

**Comment by vogdb** [comment]
where pass connection id?

**Comment by zazabe** [comment]
`janus.createConnection(<here>)`

**Comment by vogdb** [comment]
@zazabe please review

**Comment by zazabe** [comment]
lgtm!

**Pull request merged**
